Repository 1Password/shell-plugins, pull requests merged in 2023-09, with the labels that each got.

#342 Add support for Axiom CLI
  plugins/axiom/axiom.go
  plugins/axiom/personal_access_token.go
  plugins/axiom/personal_access_token_test.go
  plugins/axiom/plugin.go
  sdk/schema/fieldname/names.go
Labels: hashnode hackathon

#263 fix(new-plugin): Set only the last word of the credential name as the field name, if it's larger than seven characters
  cmd/contrib/main.go
  cmd/contrib/main_test.go
Labels: waiting-on-reviewer

#296 Add support for Civo, a managed Kubernetes service
  plugins/civo/api_key.go
  plugins/civo/api_key_test.go
  plugins/civo/civo.go
  plugins/civo/plugin.go
  plugins/civo/test-fixtures/.civo.json
Labels: waiting-on-sec-review, hashnode hackathon
